apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: dev 
  labels:
    app: my-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: rukevweubio/my-java-app-app:latest  
          ports:
            - containerPort: 8080


