
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: dev 
  labels:
    app: my-app
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - port: 8444
      targetPort: 8080
      nodePort: 30080  
